Internal error: 'with' clause failed unexpectedly in 'Foo', defined in strategy 'main'
	1
	main_0_0
	Foo_0_0
	fetch_elem_1_0
	aux_Foo_0_1
	with_1_1 <==
